---
- hosts: all
  remote_user: root 
  vars:
          NORMAL_USER_NAME: 'giac'
  tasks:
          - name: "Create a secondary, non-root user"
            user: name={{ NORMAL_USER_NAME }}
                  password= "{{ 'giac' | password_hash('sha512') }}"
                  shell= /bin/bash
          - name: Add remote authorized key to allow future passwordless logins
            authorized_key: user={{ NORMAL_USER_NAME }} key="{{ lookup('file', '/home/trfflhntr/.ssh/id_rsa.pub') }}"
          - name: Add normal user to sudoers
            lineinfile: dest=/etc/sudoers
                        regexp="{{ NORMAL_USER_NAME }} ALL"
                        line="{{ NORMAL_USER_NAME }} ALL=(ALL) ALL"
                        state=present

